version: '3.7'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "source ./env/Scripts/activate && cd megua && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src
    ports:
      - "8000:8000"
    depends_on:
      - db