# Generated by Django 2.2.5 on 2019-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meguauser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
