# Generated by Django 2.1 on 2019-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheading',
            name='Question',
            field=models.CharField(max_length=10000),
        ),
    ]
