# Generated by Django 2.1 on 2019-11-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20191024_1217'),
        ('v1', '0002_auto_20191108_1620'),
    ]

    operations = [
    ]
