# Generated by Django 2.2.5 on 2019-11-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_merge_20191108_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subheading',
            old_name='Sugestion',
            new_name='Suggestion',
        ),
        migrations.AddField(
            model_name='exercise',
            name='Solution',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Suggestion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='Tags',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
